### ISSUE TITLE
Create front-end wireframe

### ISSUE THREAD

**Issue by harrisonlingren** [harrisonlingren/myfood#3]
For anyone that stumbles upon this, here's what I am looking for for this issue:

* File/folder scaffolding for a new Angular web app
* Install necessary dependencies to package.json:
   * bower
     * angular
     * angular-material
   * gulp

**Comment by mmhansen** [comment]
What sort of front end are you looking to create? 
I could make a react front end with some components for login/logout if that's what you need

**Comment by harrisonlingren** [comment]
@mmhansen I am specifically looking to create an Angular front end for this project. For this issue specifically, my goal was to just set up the file/folder structure with whatever I needed and install any libraries necessary to get started with front end dev. I'll add what I'm looking for to the description.

**Comment by harrisonlingren** [comment]
This is under way as a part of #17 and #18
